name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create Database
      run: python app/database.py

    - name: Run websocket server
      run: python websocket_server/server.py

    - name: Run tests
      run: pytest -sv

    - name: Start FastAPI Server
      run: uvicorn app.endpoints:app --host 0.0.0.0 --port 8000 &
      continue-on-error: true

    - name: Run Locust Load Test
      run: |
        sleep 5  # Give the server a few seconds to start
        locust --headless -f tests/locustfile.py -u 10 -r 1 --run-time 1m --host http://127.0.0.1:8000

    - name: Build Docker image
      run: docker build -t mock_chatbot .

    - name: Log in to Docker Hub
      env:
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_KEY }}
      run: echo $DOCKER_ACCESS_TOKEN | docker login --username ${{ secrets.DOCKER_ACCESS_NAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push myusername/mock_chatbot
